version: '3.8'

services:
  web:
    container_name: python-docker
    build: .
    ports:
      - 80:5000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASS=p@ssw0rd1
      - DB_NAME=inventory 
    volumes:
      - ./:/app

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
volumes:
  mysql:
  mysql_config: